In [1]:
import numpy as np
import scipy
from scipy import linalg
from scipy.sparse.linalg import spsolve
import sklearn.preprocessing as sp

In [2]:
# Question 1

mat_a = np.random.uniform(0, 1, (2, 2))
mat_b = np.random.uniform(0, 1, (1, 1))
mat_c = np.random.uniform(0, 1, (2, 2))
block_mat = linalg.block_diag(mat_a, mat_b, mat_c)
print block_mat

[[ 0.52368963  0.75959492  0.          0.          0.        ]
 [ 0.27908717  0.97006306  0.          0.          0.        ]
 [ 0.          0.          0.26359317  0.          0.        ]
 [ 0.          0.          0.          0.5452098   0.86410027]
 [ 0.          0.          0.          0.04450541  0.1149176 ]]


In [3]:
# Question 2

u, s, v = linalg.svd(block_mat)
print u, "\n\n", s, "\n\n", v

[[-0.67285919  0.          0.         -0.73977058  0.        ]
 [-0.73977058  0.          0.          0.67285919  0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.         -0.99306022  0.          0.         -0.117607  ]
 [ 0.         -0.117607    0.          0.          0.99306022]] 

[ 1.34983509  1.02886184  0.26359317  0.21929995  0.02351829] 

[[-0.41399861 -0.91027751 -0.         -0.         -0.        ]
 [-0.         -0.         -0.         -0.53132528 -0.8471679 ]
 [ 0.          0.          1.          0.          0.        ]
 [-0.91027751  0.41399861  0.          0.          0.        ]
 [ 0.          0.          0.         -0.8471679   0.53132528]]


In [4]:
# Question 3

new_mat = block_mat.copy()
np.random.shuffle(new_mat)
print new_mat

[[ 0.52368963  0.75959492  0.          0.          0.        ]
 [ 0.          0.          0.26359317  0.          0.        ]
 [ 0.          0.          0.          0.04450541  0.1149176 ]
 [ 0.          0.          0.          0.5452098   0.86410027]
 [ 0.27908717  0.97006306  0.          0.          0.        ]]


In [5]:
# Question 4

u_prime, s_prime, v_prime = linalg.svd(new_mat)
print u_prime, "\n\n", s_prime, "\n\n", v_prime

[[-0.67285919  0.          0.          0.73977058  0.        ]
 [ 0.          0.         -1.          0.          0.        ]
 [ 0.         -0.117607    0.          0.          0.99306022]
 [ 0.         -0.99306022  0.          0.         -0.117607  ]
 [-0.73977058  0.          0.         -0.67285919  0.        ]] 

[ 1.34983509  1.02886184  0.26359317  0.21929995  0.02351829] 

[[-0.41399861 -0.91027751 -0.         -0.         -0.        ]
 [-0.         -0.         -0.         -0.53132528 -0.8471679 ]
 [-0.         -0.         -1.         -0.         -0.        ]
 [ 0.91027751 -0.41399861 -0.         -0.         -0.        ]
 [ 0.          0.          0.         -0.8471679   0.53132528]]


In [6]:
# Question 5
print s, "\n\n", s_prime
# permutations of the rows of the matrix does not change the singular values

[ 1.34983509  1.02886184  0.26359317  0.21929995  0.02351829] 

[ 1.34983509  1.02886184  0.26359317  0.21929995  0.02351829]


In [7]:
# Question 6

norm_vector = np.linalg.norm(new_mat, ord=1, axis=0)
unit_norm = new_mat/norm_vector
print unit_norm

[[ 0.65234774  0.43915903  0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          0.07546932  0.11738049]
 [ 0.          0.          0.          0.92453068  0.88261951]
 [ 0.34765226  0.56084097  0.          0.          0.        ]]


In [8]:
# Question 7

u_dash, s_dash, v_dash = linalg.svd(unit_norm)
print u_dash, "\n\n", s_dash, "\n\n", v_dash

[[ 0.         -0.77133144  0.          0.63643367  0.        ]
 [ 0.          0.         -1.          0.          0.        ]
 [-0.10559536  0.          0.          0.          0.99440918]
 [-0.99440918  0.          0.          0.         -0.10559536]
 [ 0.         -0.63643367  0.         -0.77133144  0.        ]] 

[ 1.28537341  1.00437471  1.          0.21226014  0.03260622] 

[[-0.         -0.         -0.         -0.72144872 -0.69246786]
 [-0.72127854 -0.69264512 -0.         -0.         -0.        ]
 [-0.         -0.         -1.         -0.         -0.        ]
 [ 0.69264512 -0.72127854 -0.         -0.         -0.        ]
 [ 0.          0.          0.         -0.69246786  0.72144872]]


In [9]:
# Question 8

vector = np.ones((1, unit_norm.shape[0]))
eigen = vector.dot(unit_norm)
print eigen
# Yes, this is an eigenvector

[[ 1.  1.  1.  1.  1.]]


In [10]:
# Question 10

indices_arr = np.transpose(np.nonzero(new_mat))
mat_prime = new_mat.copy()
for index in indices_arr:
    mat_prime[index[0]][index[1]] = 1
print mat_prime

[[ 1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.]]


In [11]:
# Question 11

vect = np.array(range(mat_prime.shape[1]))
print vect

[0 1 2 3 4]


In [12]:
# Question 12

result = np.multiply(vect, mat_prime)
i = 3  # ith row
print max(result[i])

4.0


In [13]:
# Question 13

for i in range(1000):
    result = np.multiply(vect, mat_prime)
    for j in range(vect.shape[0]):
        vect[j] = max(result[j])

print vect
# Value of each element of vect converges to n-1 where n x n is the size of the matrix

[4 4 4 4 4]


In [14]:
# Question 14

sparse_mat = scipy.sparse.rand(15000, 15000, density=0.000444445)
arr_tuple = np.nonzero(sparse_mat)
print len(arr_tuple[0])

100000


In [ ]:
# Question 15

# start_time = time.time()
ind_tuple = np.transpose(np.nonzero(sparse_mat))
sum_list = ((sparse_mat.sum(axis=0)).tolist())
sum_list = sum_list[0]
sum_val = sum(sum_list)
mean = sum_val/len(ind_tuple)
csr_mat = scipy.sparse.csr_matrix(sparse_mat)
indices_list = np.transpose(np.nonzero(csr_mat))
for indices in indices_list:
    csr_mat[indices[0], indices[1]] -= mean
# print("--- %s seconds ---" % (time.time() - start_time))

# start_time = time.time()
scaler = sp.StandardScaler(copy=True, with_mean=False, with_std=True).fit(csr_mat)
norm_mat = scaler.transform(csr_mat)
# print("--- %s seconds ---" % (time.time() - start_time))

print norm_mat, "\n\n"

rand_vect = np.random.randn(norm_mat.shape[1], 1)
dot_prod = norm_mat.dot(rand_vect)

print dot_prod

# this takes atleast twice as much time as the above code
# start_time = time.time()
# fast_tuple = scipy.sparse.find(sparse_mat)
# elements = fast_tuple[2]
# sum_val_1 = sum(elements)
# mean_1 = sum_val_1/len(elements)
# print("--- %s seconds ---" % (time.time() - start_time))